version: "3"

services:
  singlestore:
    image: memsql/cluster-in-a-box
    ports:
      - 3306:3306
      - 8080:8080
    volumes:
      # persist data between runs:
      - db-data:/var/lib/memsql
      - ./init.sql:/init.sql
    environment:
      # use the LICENSE_KEY environment variable set in the terminal:
      - LICENSE_KEY=${LICENSE_KEY}
      - START_AFTER_INIT=Y
      - ROOT_PASSWORD=root
    networks:
      - app
  app:
    build:
      context: .
    networks:
      - app
    ports:
      - 3000:3000
volumes:
  db-data:

networks:
  app:
    driver: bridge
