services:
  singlestore:
    image: memsql/cluster-in-a-box
    ports:
      - 3306:3306
      - 8080:8080
    volumes:
      # persist data between runs:
      - db-data:/var/lib/memsql
      - ./init.sql:/init.sql
    environment:
      # use the LICENSE_KEY environment variable set in the terminal:
      - LICENSE_KEY=${LICENSE_KEY}
      - START_AFTER_INIT=Y
      - ROOT_PASSWORD=root
    cpus: 4
    mem_limit: 8G
    networks:
      - net

  app:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - singlestore
    cpus: 0.5
    networks:
      - net

  forwarder:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
      - singlestore
    cpus: 0.5
    networks:
      - net

  redis:
    image: redis
    ports:
      - 6379:6379
    cpus: 0.5
    networks:
      - net
    volumes:
      - ./init.sql:/init.sql
    environment:
      - REDIS_PASSWORD=root

volumes:
  db-data:

networks:
  net:
    driver: bridge
