global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics 
    scheme: http 
    static_configs:
      - targets: ["app:3000"] 


    scrape_interval: 10s # Override global scrape interval for this job
    scrape_timeout: 5s
